In [8]:
import numpy as np
A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
print(A)
A.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


(5, 4)

In [9]:
A_sum_axis0= A.sum(axis=0) #summing over column, to reduce the row dimensions
A_sum_axis0, A_sum_axis0.shape

(array([45, 50, 55, 60]), (4,))

In [10]:
A_sum_axis1= A.sum(axis=1) #summing over row, to reduce the column dimensions
A_sum_axis1, A_sum_axis1.shape

(array([10, 26, 42, 58, 74]), (5,))

In [12]:
print(A)
A.mean(axis=0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


array([ 9., 10., 11., 12.])

In [18]:
sum_A= A.sum(axis=1, keepdims=True)
sum_A

array([[10],
       [26],
       [42],
       [58],
       [74]])

In [21]:
sum_A.shape
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [20]:
A.cumsum(axis=0)

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15, 18, 21, 24],
       [28, 32, 36, 40],
       [45, 50, 55, 60]])

In [2]:
import numpy as np
x=np.arange(4)


In [3]:
A =np.arange(20)
A=A.reshape(5,4)

In [4]:
A.shape, x.shape

((5, 4), (4,))

In [5]:
np.dot(A,x)

array([ 14,  38,  62,  86, 110])

In [6]:
x, A

(array([0, 1, 2, 3]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]))