In [2]:
import numpy as np 
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

(12,)

In [4]:
x.size

12

In [5]:
x=x.reshape(3,4)

In [6]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
#elementwise operations
x=np.array([1,2,4,8])
y=np.array([2,2,2,2])
x+y

array([ 3,  4,  6, 10])

In [10]:
#concatenation
X=np.arange(12)
X=X.reshape(3,4)
Y=np.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])
np.concatenate([X,Y],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 2,  1,  4,  3],
       [ 1,  2,  3,  4],
       [ 4,  3,  2,  1]])

In [11]:
np.concatenate([X,Y],axis=1)

array([[ 0,  1,  2,  3,  2,  1,  4,  3],
       [ 4,  5,  6,  7,  1,  2,  3,  4],
       [ 8,  9, 10, 11,  4,  3,  2,  1]])